/*
 * SPI_CONFIG.h
 *
 * Created: 12/14/2020 11:38:40 PM
 *  Author: mostafa gomaa
 */ 


#ifndef SPI_CONFIG_H_
#define SPI_CONFIG_H_

#define SPI_INTERRUPT_MODE    DISABLE_SPI_INTERRUPT

#define SPI_DATA_ORDER        SEND_MSB_FIRST

#define SPI_CLOCK_POLARITY    IDLE_LOW_POLARITY

#define SPI_CLOCK_PHASE       READ_WRITE_PHASE

#define DOUBLE_SPEED_MODE     DISABLE_DOUBLE_SPEED_MODE

#define SPI_PRESCALER_VALUE   PRESCALLER_128




#endif /* SPI_CONFIG_H_ */