/*
 * UART_CONFIG.h
 *
 * Created: 11/29/2020 2:53:19 AM
 *  Author: mostafa gomaa
 */ 


#ifndef UART_CONFIG_H_
#define UART_CONFIG_H_

#define UART_MODE  ASYNCRONOUS_MODE

#define STOP_BITS   ONE_STOP_BIT 

#define PARITY_BIT_MODE  DISABLE_PARITY_BIT

#define CHARACTER_SIZE   CHAR_SIZE_8BIT

#define BAUDRATE_VALUE   BAUDRATE_9600

#define MULTI_PROCESSOR_MODE   DISABLE_MULTIPROCESSOR_MODE

#define DOUBLE_SPEED_MODE   ENABLE_DOUBLE_SPEED_MODE

#define TRANSMITTING_INTERRUPT  DISABLE_TRANSMITTING_INTERRUPT

#define RECEIVING_INTERRUPT  DISABLE_RECEIVING_INTERRUPT

#define UDR_INTERRUPT  DISABLE_UDR_INTERRUPT

#endif /* UART_CONFIG_H_ */