/*
 * External_Interrupt_Config.h
 *
 * Created: 11/13/2020 1:07:26 AM
 *  Author: mostafa gomaa
 */ 


#ifndef EXTERNAL_INTERRUPT_CONFIG_H_
#define EXTERNAL_INTERRUPT_CONFIG_H_

#define GLOBAL_INTERRUPT_STATE   GLOBAL_INTERRUPT_STATE_ENABLE

#define EXTERNAL_INT0_TRIGGER    INT_TRIGGER_RISING_EDGE
#define EXTERNAL_INT1_TRIGGER    INT_TRIGGER_RISING_EDGE
#define EXTERNAL_INT2_TRIGGER    INT_TRIGGER_RISING_EDGE



#endif /* EXTERNAL_INTERRUPT_CONFIG_H_ */